services:
  - type: web
    name: livegram-mother-bot
    runtime: python
    rootDir: telegram-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        value: "10000"
    healthCheckPath: /health
